### PR TITLE
EDSC-1249 Fix script unresponsive error.

### PR DESCRIPTION
**Pull request by mightynimble**
See my comment on 12/13 for more info.

### CODE REVIEW

**Comment by macrouch** [comment]
I used the collection C1200216712-EDF_DEV06 and it took a long time for something to happen when I selected the service. We should give some sort of indicator that something is happening

**Comment by mightynimble** [comment]
This is the corresponding earthdata serach PR: https://github.com/nasa/earthdata-search/pull/320

**Comment by macrouch** [comment]
The spinner works well. 

When I select the service and then select Download or Order it doesn't hide the service options. The button (submit/continue) changes depending on the option, but I always see the parameter tree

**Comment by mightynimble** [comment]
It could be a set up issue. I don't see the tree hanging around...

**Review by macrouch — APPROVED** [review]

**Pull request merged**
